#!/bin/sh

environment=$1

echo "[START_SCRIPT] copying env file"
rm .env
cp ../envs/app-$environment.env .env

echo "[START_SCRIPT] starting app env=$environment"
if [ $environment = "local" ]
then
    uvicorn main:app \
        --host 0.0.0.0 \
        --port 8000 \
        --log-level warning \
        --loop uvloop \
        --interface asgi3 \
        --reload
elif [ $environment = "dev" ]
then
    # uvicorn main:app \
    #     --host 0.0.0.0 \
    #     --port 8000 \
    #     --workers 1 \
    #     --log-level warning \
    #     --loop uvloop \
    #     --interface asgi3
    uvicorn main:app \
        --host 0.0.0.0 \
        --port 8000 \
        --log-level warning \
        --loop uvloop \
        --interface asgi3 \
        --reload
elif [ $environment = "prod" ]
then
    uvicorn main:app \
        --host 0.0.0.0 \
        --port 8000 \
        --workers 2 \
        --log-level warning \
        --loop uvloop \
        --interface asgi3
else
    echo "[START_SCRIPT] invalid environment. expected local/dev/prod. got $environment"
    exit
fi
echo "[START_SCRIPT] service $service is stopped"
