"""WordPress HMAC Token Authentication"""

import base64
import hmac
import hashlib
import os
import time
import logging
from dotenv import load_dotenv

from fastapi import HTTPException, Request, status
from fastapi.security import APIKeyHeader
from fastapi import Security


logger = logging.getLogger(__name__)

# Ensure environment variables from .env are loaded before accessing them
load_dotenv()

# Temporarily hardcode the shared secret until environment variables are fixed.
# TODO: Replace with environment variable lookup when configuration is reliable.
WP_SHARED_SECRET = (
    "GZJpNBVomtNePRGdnwkocV4NKuvhzM32ueeCZNi8GZJpNBVomtNePRGdnwkocV4NKuvhzM32u"
    "eeCZNi8GZJpNBVomtNePRGdnwkocV4NKuvhzM32ueeCZNi8GZJpNBVomtNePRGdnwkocV4NKuv"
    "hzM32ueeCZNi8"
)
WP_TOKEN_TTL_SECONDS = int(os.getenv("WP_TOKEN_TTL_SECONDS", "600"))
WP_TOKEN_ALLOWED_SKEW_SECONDS = int(
    os.getenv("WP_TOKEN_ALLOWED_SKEW_SECONDS", "60")
)


wp_token_header = APIKeyHeader(
    name="X-WP-Token",
    scheme_name="WP-HMAC",
    description="Paste the token generated by WordPress. It expires in ~10 minutes.",
    auto_error=False,
)


async def verify_wp_token(
    request: Request, token: str = Security(wp_token_header)
) -> int:
    """Validate the WordPress token and return the user id."""
    if not WP_SHARED_SECRET:
        logger.error("WP_SHARED_SECRET not configured")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="server misconfigured",
        )
    if not token:
        logger.warning("wp_token missing")
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="missing token")

    try:
        decoded = base64.urlsafe_b64decode(token + "==").decode()
        user_id_str, ts_str, sig = decoded.split(":")
        user_id = int(user_id_str)
        issued_at = int(ts_str)
    except Exception:
        logger.warning("wp_token format")
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="invalid token")

    now = int(time.time())
    if issued_at > now + WP_TOKEN_ALLOWED_SKEW_SECONDS or issued_at < now - (WP_TOKEN_TTL_SECONDS + WP_TOKEN_ALLOWED_SKEW_SECONDS):
        logger.info("wp_token expired for user %s", user_id)
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="token expired")

    message = f"{user_id}{issued_at}".encode()
    expected_sig = hmac.new(WP_SHARED_SECRET.encode(), message, hashlib.sha256).hexdigest()
    if not hmac.compare_digest(expected_sig, sig):
        logger.warning(
            "wp_token bad_sig for user %s: expected %s got %s", user_id, expected_sig, sig
        )
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="invalid signature")

    request.state.current_user_id = user_id
    return user_id

